image: python:3.7

variables:
  POETRY_VIRTUALENVS_CREATE: "false"
  PIP_DISABLE_PIP_VERSION_CHECK: "on"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - test
  - deploy

before_script:
  - pip install poetry
  - poetry install

test:
  stage: test
  services:
    - name: postgres:10
      alias: db
  script:
    - python test.py

deploy:
  stage: deploy
  script:
    - poetry config pypi-token.pypi $PYPI_API_TOKEN
    - poetry publish --build
  only:
    - tags
  artifacts:
    paths:
      - dist/
