# Generated by Django 2.2.2 on 2019-07-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0005_remove_customer_default_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
