# Generated by Django 2.2.2 on 2019-07-12 07:03

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopify_sync", "0006_auto_20190712_0702"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
