# Generated by Django 2.2.2 on 2019-07-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0007_order_billing_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='OrderAddress',
        ),
    ]
