# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0011_auto_20160411_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('address1', models.CharField(max_length=256, null=True)),
                ('address2', models.CharField(max_length=256, null=True)),
                ('city', models.CharField(max_length=256, null=True)),
                ('company', models.CharField(max_length=256, null=True)),
                ('country', models.CharField(max_length=256, null=True)),
                ('country_code', models.CharField(max_length=256, null=True)),
                ('country_name', models.CharField(max_length=256, null=True)),
                ('default', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('province', models.CharField(max_length=32, null=True)),
                ('province_code', models.CharField(max_length=32, null=True)),
                ('zip', models.CharField(max_length=32, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='metafield',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Product'),
        ),
        migrations.AlterField(
            model_name='metafield',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='shopify_sync.ShippingAddress'),
        ),
    ]
