# Generated by Django 3.1 on 2020-08-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0012_auto_20200821_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='county_taxes',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
