# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 22:02
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0012_auto_20160530_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_details',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
