# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0013_auto_20160621_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=511)),
            ],
        ),
        migrations.AddField(
            model_name='carrierservice',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collect',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customcollection',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metafield',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scripttag',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartcollection',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhook',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopify_sync.Session'),
            preserve_default=False,
        ),
    ]
