# Generated by Django 3.1 on 2020-09-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify_sync", "0016_inventoryitem_inventorylevel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventorylevel",
            old_name="inventory_item_id",
            new_name="inventory_item",
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
