# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-07 07:56
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0017_auto_20160623_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
