# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-02 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import shopify_sync.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0018_auto_20161007_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_codes',
            field=jsonfield.fields.JSONField(default=shopify_sync.encoders.empty_list, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='note_attributes',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tags',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_lines',
            field=jsonfield.fields.JSONField(default=shopify_sync.encoders.empty_list, null=True),
        ),
    ]
