# Generated by Django 3.1 on 2020-09-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify_sync", "0018_auto_20200901_1744"),
    ]

    operations = [
        migrations.RemoveField(model_name="inventorylevel", name="inventory_item",),
        migrations.AddField(
            model_name="inventorylevel",
            name="inventory_item_id",
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
