# Generated by Django 3.1 on 2020-09-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify_sync", "0022_inventorylevel_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="inventory_item_id",
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
