# Generated by Django 3.1 on 2020-09-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0024_auto_20200901_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.URLField(max_length=500),
        ),
    ]
