# Generated by Django 3.1 on 2020-12-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify_sync", "0032_auto_20201215_2130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorylevel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
