# Generated by Django 3.1 on 2020-12-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0034_auto_20201217_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='variant',
        ),
        migrations.AddField(
            model_name='variant',
            name='inventoryitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopify_sync.inventoryitem'),
        ),
    ]
