# Generated by Django 3.1 on 2020-12-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0036_auto_20201223_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='inventory_item_id',
            new_name='inventory_item',
        ),
    ]
