# Generated by Django 3.1 on 2020-12-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopify_sync", "0037_auto_20201223_1119"),
    ]

    operations = [
        migrations.RemoveField(model_name="variant", name="inventory_item",),
    ]
