# Generated by Django 3.1 on 2020-12-23 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shopify_sync", "0038_remove_variant_inventory_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="inventory_item_id",
            field=models.BigIntegerField(
                null=True, unique=True, verbose_name=django.db.models.deletion.SET_NULL
            ),
        ),
    ]
